// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAMLPortal.Models;

namespace SAMLPortal.Migrations
{
	[DbContext(typeof(SAMLPortalContext))]
	[Migration("20200402083905_Init")]
	partial class Init
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 64);

			modelBuilder.Entity("SAMLPortal.Models.App", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				b.Property<string>("Description")
					.IsRequired()
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<bool>("Enabled")
					.HasColumnType("tinyint(1)");

				b.Property<string>("Issuer")
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<string>("MetadataURL")
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<string>("Name")
					.IsRequired()
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<string>("SignatureValidationCertificate")
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<string>("SingleLogoutResponseDestination")
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<string>("SingleSignOnDestination")
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.HasKey("Id");

				b.ToTable("App");
			});

			modelBuilder.Entity("SAMLPortal.Models.KeyValue", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasColumnType("int");

				b.Property<string>("Key")
					.IsRequired()
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.Property<string>("Value")
					.IsRequired()
					.HasColumnType("longtext CHARACTER SET utf8mb4");

				b.HasKey("Id");

				b.ToTable("KeyValue");
			});
#pragma warning restore 612, 618
		}
	}
}